# Generated by Django 3.0.9 on 2020-12-21 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDrills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drills.Drill')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drills', models.ManyToManyField(blank=True, null=True, through='training_sessions.SessionDrills', to='drills.Drill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sessiondrills',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training_sessions.TrainingSession'),
        ),
    ]
