# Generated by Django 3.0.9 on 2020-12-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondrills',
            name='order',
            field=models.IntegerField(default=99),
        ),
    ]
