# Generated by Django 3.0.9 on 2021-04-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
        ('training_sessions', '0002_auto_20201228_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondrills',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.Drill'),
        ),
        migrations.AlterField(
            model_name='sessiondrills',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_sessions.TrainingSession'),
        ),
    ]
