# Generated by Django 3.0.9 on 2020-08-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
