# Generated by Django 3.0.9 on 2021-04-18 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
